### ISSUE TITLE
a burak bardzo czerwony?

### ISSUE THREAD

**Issue by adamczubat** [acit13920/brawo-ja#2]
oby bo baba co go z dziadem brała będzie zła

**Comment by acit13920** [comment]
A to baba nie siała mak?

**Comment by acit13920** [comment]
Ten co go rak zjadł wspak?

**Comment by acit13920** [comment]
Tak czy tak, jest tego spory brak

**Comment by adamczubat** [comment]
Bierz tego mniej 
:-)
